// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kpay.proto

package kpay

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Coin int32

const (
	Coin_DCR Coin = 0
)

var Coin_name = map[int32]string{
	0: "DCR",
}

var Coin_value = map[string]int32{
	"DCR": 0,
}

func (x Coin) String() string {
	return proto.EnumName(Coin_name, int32(x))
}

func (Coin) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a45bb491f5f51db, []int{0}
}

type RegisterPaymentInput struct {
	Amount               int64    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Coin                 Coin     `protobuf:"varint,2,opt,name=coin,proto3,enum=kpay.Coin" json:"coin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterPaymentInput) Reset()         { *m = RegisterPaymentInput{} }
func (m *RegisterPaymentInput) String() string { return proto.CompactTextString(m) }
func (*RegisterPaymentInput) ProtoMessage()    {}
func (*RegisterPaymentInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a45bb491f5f51db, []int{0}
}

func (m *RegisterPaymentInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterPaymentInput.Unmarshal(m, b)
}
func (m *RegisterPaymentInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterPaymentInput.Marshal(b, m, deterministic)
}
func (m *RegisterPaymentInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterPaymentInput.Merge(m, src)
}
func (m *RegisterPaymentInput) XXX_Size() int {
	return xxx_messageInfo_RegisterPaymentInput.Size(m)
}
func (m *RegisterPaymentInput) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterPaymentInput.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterPaymentInput proto.InternalMessageInfo

func (m *RegisterPaymentInput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *RegisterPaymentInput) GetCoin() Coin {
	if m != nil {
		return m.Coin
	}
	return Coin_DCR
}

type RegisterPaymentOutput struct {
	PaymentId            string   `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Coin                 Coin     `protobuf:"varint,3,opt,name=coin,proto3,enum=kpay.Coin" json:"coin,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	GoodUntill           int64    `protobuf:"varint,5,opt,name=good_untill,json=goodUntill,proto3" json:"good_untill,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterPaymentOutput) Reset()         { *m = RegisterPaymentOutput{} }
func (m *RegisterPaymentOutput) String() string { return proto.CompactTextString(m) }
func (*RegisterPaymentOutput) ProtoMessage()    {}
func (*RegisterPaymentOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a45bb491f5f51db, []int{1}
}

func (m *RegisterPaymentOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterPaymentOutput.Unmarshal(m, b)
}
func (m *RegisterPaymentOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterPaymentOutput.Marshal(b, m, deterministic)
}
func (m *RegisterPaymentOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterPaymentOutput.Merge(m, src)
}
func (m *RegisterPaymentOutput) XXX_Size() int {
	return xxx_messageInfo_RegisterPaymentOutput.Size(m)
}
func (m *RegisterPaymentOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterPaymentOutput.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterPaymentOutput proto.InternalMessageInfo

func (m *RegisterPaymentOutput) GetPaymentId() string {
	if m != nil {
		return m.PaymentId
	}
	return ""
}

func (m *RegisterPaymentOutput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *RegisterPaymentOutput) GetCoin() Coin {
	if m != nil {
		return m.Coin
	}
	return Coin_DCR
}

func (m *RegisterPaymentOutput) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RegisterPaymentOutput) GetGoodUntill() int64 {
	if m != nil {
		return m.GoodUntill
	}
	return 0
}

func init() {
	proto.RegisterEnum("kpay.Coin", Coin_name, Coin_value)
	proto.RegisterType((*RegisterPaymentInput)(nil), "kpay.RegisterPaymentInput")
	proto.RegisterType((*RegisterPaymentOutput)(nil), "kpay.RegisterPaymentOutput")
}

func init() { proto.RegisterFile("kpay.proto", fileDescriptor_8a45bb491f5f51db) }

var fileDescriptor_8a45bb491f5f51db = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x2e, 0x48, 0xac,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xfc, 0xb8, 0x44, 0x82, 0x52,
	0xd3, 0x33, 0x8b, 0x4b, 0x52, 0x8b, 0x02, 0x12, 0x2b, 0x73, 0x53, 0xf3, 0x4a, 0x3c, 0xf3, 0x0a,
	0x4a, 0x4b, 0x84, 0xc4, 0xb8, 0xd8, 0x12, 0x73, 0xf3, 0x4b, 0xf3, 0x4a, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x98, 0x83, 0xa0, 0x3c, 0x21, 0x39, 0x2e, 0x96, 0xe4, 0xfc, 0xcc, 0x3c, 0x09, 0x26, 0x05,
	0x46, 0x0d, 0x3e, 0x23, 0x2e, 0x3d, 0xb0, 0x81, 0xce, 0xf9, 0x99, 0x79, 0x41, 0x60, 0x71, 0xa5,
	0x95, 0x8c, 0x5c, 0xa2, 0x68, 0x06, 0xfa, 0x97, 0x96, 0x80, 0x4c, 0x94, 0xe5, 0xe2, 0x2a, 0x80,
	0x08, 0xc4, 0x67, 0xa6, 0x80, 0x4d, 0xe5, 0x0c, 0xe2, 0x84, 0x8a, 0x78, 0xa6, 0x20, 0x59, 0xc8,
	0x84, 0xd5, 0x42, 0x66, 0xec, 0x16, 0x0a, 0x49, 0x70, 0xb1, 0x27, 0xa6, 0xa4, 0x14, 0xa5, 0x16,
	0x17, 0x4b, 0xb0, 0x80, 0xcd, 0x84, 0x71, 0x85, 0xe4, 0xb9, 0xb8, 0xd3, 0xf3, 0xf3, 0x53, 0xe2,
	0x4b, 0xf3, 0x4a, 0x32, 0x73, 0x72, 0x24, 0x58, 0xc1, 0xc6, 0x72, 0x81, 0x84, 0x42, 0xc1, 0x22,
	0x5a, 0xfc, 0x5c, 0x2c, 0x20, 0x83, 0x84, 0xd8, 0xb9, 0x98, 0x5d, 0x9c, 0x83, 0x04, 0x18, 0x8c,
	0x22, 0xb8, 0xd8, 0xa1, 0x6e, 0x16, 0xf2, 0xe5, 0x12, 0x08, 0x4a, 0x2d, 0x46, 0xf1, 0x87, 0x90,
	0x14, 0xc4, 0x72, 0x6c, 0xe1, 0x25, 0x25, 0x8d, 0x55, 0x0e, 0xe2, 0x75, 0x25, 0x86, 0x24, 0x36,
	0x70, 0x98, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x44, 0x4b, 0xda, 0x73, 0x81, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PaymentClient is the client API for Payment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PaymentClient interface {
	ResgisterPayment(ctx context.Context, in *RegisterPaymentInput, opts ...grpc.CallOption) (*RegisterPaymentOutput, error)
}

type paymentClient struct {
	cc *grpc.ClientConn
}

func NewPaymentClient(cc *grpc.ClientConn) PaymentClient {
	return &paymentClient{cc}
}

func (c *paymentClient) ResgisterPayment(ctx context.Context, in *RegisterPaymentInput, opts ...grpc.CallOption) (*RegisterPaymentOutput, error) {
	out := new(RegisterPaymentOutput)
	err := c.cc.Invoke(ctx, "/kpay.Payment/ResgisterPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServer is the server API for Payment service.
type PaymentServer interface {
	ResgisterPayment(context.Context, *RegisterPaymentInput) (*RegisterPaymentOutput, error)
}

func RegisterPaymentServer(s *grpc.Server, srv PaymentServer) {
	s.RegisterService(&_Payment_serviceDesc, srv)
}

func _Payment_ResgisterPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPaymentInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).ResgisterPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kpay.Payment/ResgisterPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).ResgisterPayment(ctx, req.(*RegisterPaymentInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Payment_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kpay.Payment",
	HandlerType: (*PaymentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResgisterPayment",
			Handler:    _Payment_ResgisterPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kpay.proto",
}
